"""create_goal_instances_and_reminders

Revision ID: 1f2abf5fa7c8
Revises: 426c10a1146d
Create Date: 2026-09-27 09:08:27.463752

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f2abf5fa7c8"
down_revision: str | None = "426c10a1146d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goal_instances",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("goal_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("period_key", sa.String(length=50), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("goal_id", "period_key", name="uq_goal_instance_goal_period"),
    )
    op.create_index(op.f("ix_goal_instances_goal_id"), "goal_instances", ["goal_id"], unique=False)
    op.create_index(
        "ix_goal_instances_goal_status", "goal_instances", ["goal_id", "status"], unique=False
    )
    op.create_index(op.f("ix_goal_instances_status"), "goal_instances", ["status"], unique=False)
    op.create_index(op.f("ix_goal_instances_user_id"), "goal_instances", ["user_id"], unique=False)
    op.create_index(
        "ix_goal_instances_user_scheduled",
        "goal_instances",
        ["user_id", "scheduled_date"],
        unique=False,
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("goal_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("reminder_time", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_period_key", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_reminders_due_check", "reminders", ["is_enabled", "timezone"], unique=False)
    op.create_index(op.f("ix_reminders_goal_id"), "reminders", ["goal_id"], unique=False)
    op.create_index(op.f("ix_reminders_is_enabled"), "reminders", ["is_enabled"], unique=False)
    op.create_index("ix_reminders_user_goal", "reminders", ["user_id", "goal_id"], unique=False)
    op.create_index(op.f("ix_reminders_user_id"), "reminders", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminders_user_id"), table_name="reminders")
    op.drop_index("ix_reminders_user_goal", table_name="reminders")
    op.drop_index(op.f("ix_reminders_is_enabled"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_goal_id"), table_name="reminders")
    op.drop_index("ix_reminders_due_check", table_name="reminders")
    op.drop_table("reminders")
    op.drop_index("ix_goal_instances_user_scheduled", table_name="goal_instances")
    op.drop_index(op.f("ix_goal_instances_user_id"), table_name="goal_instances")
    op.drop_index(op.f("ix_goal_instances_status"), table_name="goal_instances")
    op.drop_index("ix_goal_instances_goal_status", table_name="goal_instances")
    op.drop_index(op.f("ix_goal_instances_goal_id"), table_name="goal_instances")
    op.drop_table("goal_instances")
    # ### end Alembic commands ###
