"""complete_world_schema

Revision ID: d6f19d6a714f
Revises: abd1e98e394c
Create Date: 2026-09-27 20:49:35.017406

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6f19d6a714f"
down_revision: str | None = "abd1e98e394c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_editions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("edition_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("lead_summary", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_editions_edition_date"), "daily_editions", ["edition_date"], unique=True
    )
    op.create_table(
        "diary_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mood", sa.String(length=50), nullable=True),
        sa.Column("reflection_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "entry_date", name="uq_user_diary_entry_date"),
    )
    op.create_index(
        op.f("ix_diary_entries_entry_date"), "diary_entries", ["entry_date"], unique=False
    )
    op.create_index(
        "ix_diary_entries_user_date", "diary_entries", ["user_id", "entry_date"], unique=False
    )
    op.create_index(op.f("ix_diary_entries_user_id"), "diary_entries", ["user_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_is_archived"), "notes", ["is_archived"], unique=False)
    op.create_index(op.f("ix_notes_is_pinned"), "notes", ["is_pinned"], unique=False)
    op.create_index("ix_notes_user_archived", "notes", ["user_id", "is_archived"], unique=False)
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    op.create_index("ix_notes_user_pinned", "notes", ["user_id", "is_pinned"], unique=False)
    op.create_index("ix_notes_user_updated", "notes", ["user_id", "updated_at"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("technologies", sa.JSON(), nullable=False),
        sa.Column("github_url", sa.String(length=1000), nullable=True),
        sa.Column("live_url", sa.String(length=1000), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("completion_date", sa.Date(), nullable=True),
        sa.Column("lessons_learned", sa.Text(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_is_featured"), "projects", ["is_featured"], unique=False)
    op.create_index(
        "ix_projects_user_featured", "projects", ["user_id", "is_featured"], unique=False
    )
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_index("ix_projects_user_order", "projects", ["user_id", "order_index"], unique=False)
    op.create_index("ix_projects_user_status", "projects", ["user_id", "status"], unique=False)
    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("scheduled_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_jobs_job_name"), "scheduled_jobs", ["job_name"], unique=False
    )
    op.create_index(
        "ix_scheduled_jobs_name_time",
        "scheduled_jobs",
        ["job_name", "scheduled_time"],
        unique=False,
    )
    op.create_index("ix_scheduled_jobs_status", "scheduled_jobs", ["status"], unique=False)
    op.create_table(
        "story_chapters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("period", sa.String(length=100), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("milestones", sa.JSON(), nullable=False),
        sa.Column("reflections", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_chapters_user_id"), "story_chapters", ["user_id"], unique=False)
    op.create_index(
        "ix_story_chapters_user_order", "story_chapters", ["user_id", "order_index"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("news_daily_update", sa.Boolean(), nullable=False),
        sa.Column("news_update_time", sa.String(length=10), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("notification_channels", sa.JSON(), nullable=False),
        sa.Column("reduced_motion", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_preferences_user_id"), "user_preferences", ["user_id"], unique=True
    )
    op.create_table(
        "daily_edition_articles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("edition_id", sa.String(length=36), nullable=False),
        sa.Column("article_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["news_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["edition_id"], ["daily_editions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("edition_id", "article_id", name="uq_daily_edition_article"),
    )
    op.create_index(
        op.f("ix_daily_edition_articles_article_id"),
        "daily_edition_articles",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_edition_articles_edition_id"),
        "daily_edition_articles",
        ["edition_id"],
        unique=False,
    )
    op.create_index(
        "ix_edition_articles_position",
        "daily_edition_articles",
        ["edition_id", "position"],
        unique=False,
    )
    op.create_table(
        "user_article_reads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("article_id", sa.String(length=36), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["news_articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "article_id", name="uq_user_article_read"),
    )
    op.create_index(
        op.f("ix_user_article_reads_article_id"), "user_article_reads", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_article_reads_user_id"), "user_article_reads", ["user_id"], unique=False
    )
    op.create_index(
        "ix_user_article_reads_user_read_at",
        "user_article_reads",
        ["user_id", "read_at"],
        unique=False,
    )
    op.add_column("news_articles", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("news_articles", sa.Column("key_points", sa.JSON(), nullable=True))
    op.add_column("news_articles", sa.Column("why_it_matters", sa.Text(), nullable=True))
    op.add_column(
        "news_articles",
        sa.Column("summary_status", sa.String(length=50), server_default="none", nullable=False),
    )
    op.add_column(
        "news_articles", sa.Column("summary_provider", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_articles", "summary_provider")
    op.drop_column("news_articles", "summary_status")
    op.drop_column("news_articles", "why_it_matters")
    op.drop_column("news_articles", "key_points")
    op.drop_column("news_articles", "summary")
    op.drop_index("ix_user_article_reads_user_read_at", table_name="user_article_reads")
    op.drop_index(op.f("ix_user_article_reads_user_id"), table_name="user_article_reads")
    op.drop_index(op.f("ix_user_article_reads_article_id"), table_name="user_article_reads")
    op.drop_table("user_article_reads")
    op.drop_index("ix_edition_articles_position", table_name="daily_edition_articles")
    op.drop_index(op.f("ix_daily_edition_articles_edition_id"), table_name="daily_edition_articles")
    op.drop_index(op.f("ix_daily_edition_articles_article_id"), table_name="daily_edition_articles")
    op.drop_table("daily_edition_articles")
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index("ix_story_chapters_user_order", table_name="story_chapters")
    op.drop_index(op.f("ix_story_chapters_user_id"), table_name="story_chapters")
    op.drop_table("story_chapters")
    op.drop_index("ix_scheduled_jobs_status", table_name="scheduled_jobs")
    op.drop_index("ix_scheduled_jobs_name_time", table_name="scheduled_jobs")
    op.drop_index(op.f("ix_scheduled_jobs_job_name"), table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index("ix_projects_user_status", table_name="projects")
    op.drop_index("ix_projects_user_order", table_name="projects")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_index("ix_projects_user_featured", table_name="projects")
    op.drop_index(op.f("ix_projects_is_featured"), table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_notes_user_updated", table_name="notes")
    op.drop_index("ix_notes_user_pinned", table_name="notes")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.drop_index("ix_notes_user_archived", table_name="notes")
    op.drop_index(op.f("ix_notes_is_pinned"), table_name="notes")
    op.drop_index(op.f("ix_notes_is_archived"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_diary_entries_user_id"), table_name="diary_entries")
    op.drop_index("ix_diary_entries_user_date", table_name="diary_entries")
    op.drop_index(op.f("ix_diary_entries_entry_date"), table_name="diary_entries")
    op.drop_table("diary_entries")
    op.drop_index(op.f("ix_daily_editions_edition_date"), table_name="daily_editions")
    op.drop_table("daily_editions")
    # ### end Alembic commands ###
