"""create_achievements_table

Revision ID: 8ae111ef16b4
Revises: 1f2abf5fa7c8
Create Date: 2026-09-27 13:11:29.134976

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ae111ef16b4"
down_revision: str | None = "1f2abf5fa7c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("milestone_key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("icon", sa.String(length=10), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("achieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "milestone_key", name="uq_achievement_user_milestone"),
    )
    op.create_index(op.f("ix_achievements_source_id"), "achievements", ["source_id"], unique=False)
    op.create_index(
        "ix_achievements_user_achieved_at", "achievements", ["user_id", "achieved_at"], unique=False
    )
    op.create_index(
        "ix_achievements_user_category", "achievements", ["user_id", "category"], unique=False
    )
    op.create_index(op.f("ix_achievements_user_id"), "achievements", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_achievements_user_id"), table_name="achievements")
    op.drop_index("ix_achievements_user_category", table_name="achievements")
    op.drop_index("ix_achievements_user_achieved_at", table_name="achievements")
    op.drop_index(op.f("ix_achievements_source_id"), table_name="achievements")
    op.drop_table("achievements")
    # ### end Alembic commands ###
