"""create_news_tables

Revision ID: abd1e98e394c
Revises: 8ae111ef16b4
Create Date: 2026-09-27 14:10:06.765706

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abd1e98e394c"
down_revision: str | None = "8ae111ef16b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("feed_url", sa.String(length=1000), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("reliability_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_sources_category"), "news_sources", ["category"], unique=False)
    op.create_index(
        "ix_news_sources_category_enabled", "news_sources", ["category", "is_enabled"], unique=False
    )
    op.create_index(op.f("ix_news_sources_feed_url"), "news_sources", ["feed_url"], unique=True)
    op.create_index(
        op.f("ix_news_sources_is_enabled"), "news_sources", ["is_enabled"], unique=False
    )
    op.create_table(
        "news_articles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=True),
        sa.Column("canonical_url", sa.String(length=1000), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["news_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_articles_canonical_url"), "news_articles", ["canonical_url"], unique=True
    )
    op.create_index(op.f("ix_news_articles_category"), "news_articles", ["category"], unique=False)
    op.create_index(
        "ix_news_articles_category_published",
        "news_articles",
        ["category", "published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_articles_external_id"), "news_articles", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_news_articles_published_at"), "news_articles", ["published_at"], unique=False
    )
    op.create_index(
        "ix_news_articles_source_external",
        "news_articles",
        ["source_id", "external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_articles_source_id"), "news_articles", ["source_id"], unique=False
    )
    op.create_index(
        "ix_news_articles_source_published",
        "news_articles",
        ["source_id", "published_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_news_articles_source_published", table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_source_id"), table_name="news_articles")
    op.drop_index("ix_news_articles_source_external", table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_published_at"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_external_id"), table_name="news_articles")
    op.drop_index("ix_news_articles_category_published", table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_category"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_canonical_url"), table_name="news_articles")
    op.drop_table("news_articles")
    op.drop_index(op.f("ix_news_sources_is_enabled"), table_name="news_sources")
    op.drop_index(op.f("ix_news_sources_feed_url"), table_name="news_sources")
    op.drop_index("ix_news_sources_category_enabled", table_name="news_sources")
    op.drop_index(op.f("ix_news_sources_category"), table_name="news_sources")
    op.drop_table("news_sources")
    # ### end Alembic commands ###
